# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "AWS tooling for faster development."
  homepage "https://www.flowlab.no/"
  url "https://github.com/flow-lab/flow/releases/download/v0.1.54/flow_Darwin_x86_64.tar.gz"
  version "0.1.54"
  sha256 "dac5acfbd2d186459e32f1d7571dd620a9bb04e64c58eee884377e003beaa6fc"

  def install
    bin.install "flow"
  end

  test do
    system "#{bin}/flow --version"
  end
end
