# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "AWS tooling for faster development."
  homepage "https://www.flowlab.no/"
  version "0.1.69"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/flow-lab/flow/releases/download/v0.1.69/flow_Darwin_x86_64.tar.gz"
    sha256 "095e7eaba5aeb7b331f5f1ac1728f4012bad646c5854e37b3441ab3ef9972ac3"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/flow-lab/flow/releases/download/v0.1.69/flow_Linux_x86_64.tar.gz"
      sha256 "e8c26b1127bf17c047af2f18180af4191dffef5abf264fabeec9078a53ee649a"
    end
  end

  def install
    bin.install "flow"
  end

  test do
    system "#{bin}/flow --version"
  end
end
