# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Flow < Formula
  desc "AWS tooling for faster development."
  homepage "https://www.flowlab.no/"
  version "0.5.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/flow-lab/flow/releases/download/v0.5.2/flow_Darwin_x86_64.tar.gz"
      sha256 "f9dd17d45de604ef8e605c034d6934b7ac412da7b8f79c8a143fbce154820821"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/flow-lab/flow/releases/download/v0.5.2/flow_Darwin_aarch64.tar.gz"
      sha256 "fc080f0ad45241f1cc5fdf090e75350029cd4daa9a797b351fa4bf639e2e68a2"

      def install
        bin.install "flow"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/flow-lab/flow/releases/download/v0.5.2/flow_Linux_x86_64.tar.gz"
      sha256 "e3631fbeff9a1b7d9a152dd4ae72b5caaa51993c7b66435d725052fbe82435a5"

      def install
        bin.install "flow"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/flow-lab/flow/releases/download/v0.5.2/flow_Linux_aarch64.tar.gz"
      sha256 "574b7d05fc27a537cdfea92c162b44027296485e492384883938fd57bb211dd0"

      def install
        bin.install "flow"
      end
    end
  end

  test do
    system "#{bin}/flow --version"
  end
end
